config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :flats, only: [:index, :new, :show, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController

  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.new
      redirect_to flats_path, notice: "Apartement added with success"
    else
      render :new
    end
  end

  def edit
    @flat = Flat.find(params[:id])
  end

  def update
    @flat = Flat.find(params[:id])
    if @flat.update(flat_params)
      redirect_to @flat, notice: 'Appartement mis à jour avec succès.'
    else
      render :edit
    end
  end

  def destroy
    @flat = Flat.find(params[:id])
    @flat.destroy
    redirect_to @flats, notice: 'Appartement bien supprimé'
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :description, :address, :price_per_night, :number_of_guests)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= simple_form_for(@flat) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests %>
  <%= f.button :submit %>
<% end %>

app/views/flats/edit.html.erb
<%= render 'form', flat: @flat %>

app/views/flats/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 d-flex justify-content-between align-items-center">
      <h1>All our flats (<%= @flats.count %>)</h1>
      <%= link_to 'Ajouter un nouvel appartement', new_flat_path, class: "btn btn-primary" %>
    </div>
  </div>
  <% @flats.each do |flat| %>
  <div class="card mb-3">
    <div class="card-body">
      <h5 class="card-title"> <%= link_to flat.name, flat_path(flat) %></h5>
      <h6 class="card-subtitle mb-2 text-muted"><%= flat.address %></h6>
      <p class="card-text"><%= flat.description %></p>
      <p class="card-text"><strong>Prix par nuit :</strong> <%= flat.price_per_night %>€</p>
      <p class="card-text"><strong>Capacité :</strong> <%= flat.number_of_guests %> personnes</p>
      <%= link_to "Edit", edit_flat_path(flat), data: { confirm: "Êtes-vous sûr de vouloir modifier cet appartement ?" } %>
      <%= link_to "Supprimer", flat_path(flat), method: :delete, data: { confirm: "Êtes-vous sûr de vouloir supprimer cet appartement ?" } %>
    </div>
  </div>
  <% end %>
</div>

app/views/flats/new.html.erb
<h1>Ajouter un nouvel appartement</h1>

<%= render 'form', flat: @flat %>

app/views/flats/show.html.erb
<h1><%= @flat.name %></h1>
<p><%= @flat.description %></p>
<p><%= @flat.address %></p>
<p>Prix par nuit : <%= @flat.price_per_night %>€</p>
<p>Capacité : <%= @flat.number_of_guests %> personnes</p>
<%= link_to "Supprimer", flat_path(@flat), method: :delete, data: { confirm: "Êtes-vous sûr de vouloir supprimer cet appartement ?" } %>
<%= link_to "Edit", edit_flat_path(@flat), data: { confirm: "Êtes-vous sûr de vouloir modifier cet appartement ?" } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>